parent_dir = "exp/totalturnover/ctabgan-plus/"
real_data_path = "data/totalturnover"
seed = 0
device = "cuda"

[train_params]
lr = 0.0007730469768343876
epochs = 10000
class_dim = [
    128,
]
batch_size = 1024
random_dim = 128
num_channels = 32

[sample]
seed = 0
num_samples = 4272

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
