seed = 0
parent_dir = "exp/metro/ddpm_tune_best"
real_data_path = "data/metro/"
model_type = "mlp"
num_numerical_features = 5
device = "cuda:0"

[model_params]
is_y_cond = false
num_classes = 0

[model_params.rtdl_params]
d_layers = [
    1024,
    1024,
    1024,
    1024,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 20000
lr = 0.001634604862685541
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "minmax"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"

[sample]
num_samples = 2286
batch_size = 100
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
